# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jackin < Formula
  desc "tmux-native multi-agent swarm orchestrator"
  homepage "https://github.com/AdriaanVE/jack-in"
  version "0.1.1"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.1/jackin_darwin_amd64.tar.gz"
      sha256 "6d67582370b99e83311101de0cec52f981dcd12e38e79740810178a213f56132"

      define_method(:install) do
        bin.install "jackin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.1/jackin_darwin_arm64.tar.gz"
      sha256 "646d7a10606fdf571343c6b1dd3a6ce56f0416e318fa58348d20828029b7411d"

      define_method(:install) do
        bin.install "jackin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.1/jackin_linux_amd64.tar.gz"
      sha256 "6888fffff0698e5e9708f17dbc8b13273daa9ac9df1982c2c86748f58f064a8b"
      define_method(:install) do
        bin.install "jackin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.1/jackin_linux_arm64.tar.gz"
      sha256 "49f33d025f99812a98ac8a1f8b64566f89bb0215c6a9df7bcfd94782230d863b"
      define_method(:install) do
        bin.install "jackin"
      end
    end
  end

  test do
    assert_match "jackin", shell_output("#{bin}/jackin --help")
  end
end
