# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jackin < Formula
  desc "tmux-native multi-agent swarm orchestrator"
  homepage "https://github.com/AdriaanVE/jack-in"
  version "0.1.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.0/jackin_darwin_amd64.tar.gz"
      sha256 "806d28f331c938c2c39ceb8c5f4c719e2ac9e38585c678263c426aa33432969f"

      define_method(:install) do
        bin.install "jackin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.0/jackin_darwin_arm64.tar.gz"
      sha256 "9b4df401d179e0c5b410937176ff44676c26c9a004ffae8e09a4a7318981aeb1"

      define_method(:install) do
        bin.install "jackin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.0/jackin_linux_amd64.tar.gz"
      sha256 "93e787891f6d57a8cb7a8bf522abe2d2bd7534cb76c62087e5ff7f0f35d972a5"
      define_method(:install) do
        bin.install "jackin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.0/jackin_linux_arm64.tar.gz"
      sha256 "46960ecff4fb0015f5ff08b5e2e379e75177e5947149145e605d4807a703b212"
      define_method(:install) do
        bin.install "jackin"
      end
    end
  end

  test do
    assert_match "jackin", shell_output("#{bin}/jackin --help")
  end
end
