# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jackin < Formula
  desc "tmux-native multi-agent swarm orchestrator"
  homepage "https://github.com/AdriaanVE/jack-in"
  version "0.1.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.0/jackin_darwin_amd64.tar.gz"
      sha256 "cc7ce2c41c5ff6cc2dd5fa438ddbe912a528a771742a33c200ca0241b776a171"

      define_method(:install) do
        bin.install "jackin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.0/jackin_darwin_arm64.tar.gz"
      sha256 "7fa11372f364f7e4182ac7715cd08d86c6c7c153d011c7b0d5f2d0240445bd52"

      define_method(:install) do
        bin.install "jackin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.0/jackin_linux_amd64.tar.gz"
      sha256 "b34967fffd2bbf8f9f0f08846513eb64d6ed70767c54206da05ce1367f0660ce"
      define_method(:install) do
        bin.install "jackin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AdriaanVE/jack-in/releases/download/v0.1.0/jackin_linux_arm64.tar.gz"
      sha256 "b71610bff7c9545b7349822dffb012efb1edee1dca357798e25660163463198d"
      define_method(:install) do
        bin.install "jackin"
      end
    end
  end

  test do
    assert_match "jackin", shell_output("#{bin}/jackin --help")
  end
end
